In [6]:
import numpy as np

Criando array

In [17]:
num = np.ones((4, 3))
print(num)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Criar matriz 3 dimensoes com 4 camadas de profundidate, 3 linhas e 2 colunas

In [18]:
num = np.ones((4, 3, 2))
print(num)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [19]:
n = np.zeros((2,3,4), dtype = np.int32)

In [20]:
print(n)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [26]:
n = np.random.random((2,3))
print(n)

[[0.3567027  0.10542325 0.86761331]
 [0.60691657 0.04074779 0.99292541]]


In [31]:
n =np.full((3,4), 7)
print(n)

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [33]:
n = np.arange(10,25,2)
print(n)

[10 12 14 16 18 20 22 24]


In [45]:
n = n.reshape(2,4)
print(n)

[[10 12 14 16]
 [18 20 22 24]]


In [46]:
n.reshape(2,2,2)

array([[[10, 12],
        [14, 16]],

       [[18, 20],
        [22, 24]]])

In [41]:
n.ndim

2

In [42]:
n.shape

(2, 4)

In [43]:
n.size

8

In [44]:
n.shape[0]

2

In [51]:
a = np.identity(5)
b = np.random.random((3,5))
print(a, b)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] [[0.5137267  0.08801087 0.96483016 0.78157275 0.209665  ]
 [0.16131081 0.31689022 0.36184074 0.01857999 0.27202849]
 [0.19994974 0.65976775 0.89861632 0.7355853  0.37769125]]


In [52]:
res = np.dot(b,a)

In [53]:
print(res)

[[0.5137267  0.08801087 0.96483016 0.78157275 0.209665  ]
 [0.16131081 0.31689022 0.36184074 0.01857999 0.27202849]
 [0.19994974 0.65976775 0.89861632 0.7355853  0.37769125]]


In [54]:
res.shape

(3, 5)

In [55]:
res.size

15

In [58]:
res.ndim

2

In [60]:
type(res)

numpy.ndarray

In [57]:
b.transpose()

array([[0.5137267 , 0.16131081, 0.19994974],
       [0.08801087, 0.31689022, 0.65976775],
       [0.96483016, 0.36184074, 0.89861632],
       [0.78157275, 0.01857999, 0.7355853 ],
       [0.209665  , 0.27202849, 0.37769125]])

#### sum(axis = 0) somatorio de todas as linhas  
#### sum(axis = 1) somatorio de todas as colunas  
#### sum(axis = none) somatorio na forma snakegame  

In [62]:
lista = [[1,2,3],[2,0,0]]

In [66]:
lista_a = np.asarray(lista)

In [79]:
print(type(lista_a),lista_a.shape)

<class 'numpy.ndarray'> (2, 3)


In [82]:
soma_das_linhas = lista_a.sum(axis=0)
soma_das_colunas = lista_a.sum(axis=1)

In [83]:
print(soma_das_linhas, soma_das_colunas)

[3 2 3] [6 2]


In [86]:
lista_b = lista_a.reshape(3,2)
print(lista_b)

[[1 2]
 [3 2]
 [0 0]]


In [85]:
resul_b = lista_b.sum(axis=0)
print(resul_b)

[4 4]


In [90]:
print(type(list(resul_b)))

<class 'list'>


In [91]:
asd = np.eye(500)

In [92]:
print(asd)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [93]:
lista = [['Sem Informacoes', 'teste'],['Sem informacoes','Sem informacoes']]

In [94]:
lista

[['Sem Informacoes', 'teste'], ['Sem informacoes', 'Sem informacoes']]

In [95]:
arr = np.asarray(lista)

In [99]:
arr

array([['Sem Informacoes', 'teste'],
       ['Sem informacoes', 'Sem informacoes']], dtype='<U15')

# Exercicios NUMPY

In [104]:
array10 = np.arange(1,21,2)
print(array10)

[ 1  3  5  7  9 11 13 15 17 19]


In [105]:
array10.size

10

In [107]:
array10 = array10.reshape(2,5)
print(array10)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]


In [125]:
matriz_bi1 = np.random.random((4,4,4))
print(matriz_bi1)

[[[0.82551145 0.06594912 0.06031687 0.70734317]
  [0.10619492 0.80207753 0.53083228 0.39075805]
  [0.07084524 0.92795872 0.46272771 0.08108519]
  [0.7124669  0.98180599 0.83349487 0.09190924]]

 [[0.75702447 0.78533284 0.83109745 0.1119558 ]
  [0.56239781 0.88640062 0.87001532 0.29470137]
  [0.78151744 0.99877733 0.11871717 0.91430094]
  [0.99765798 0.7288297  0.45507218 0.27992281]]

 [[0.35496962 0.76846832 0.52203325 0.57836048]
  [0.4862526  0.01475294 0.50609739 0.93716861]
  [0.63110711 0.97681767 0.77389332 0.47907545]
  [0.56526989 0.98367796 0.17820333 0.39872234]]

 [[0.71070702 0.7971604  0.81260405 0.64039519]
  [0.20868981 0.0513841  0.08802734 0.61424239]
  [0.7082305  0.05142895 0.10317148 0.00601467]
  [0.60582155 0.49385031 0.37473742 0.69359128]]]


In [126]:
matriz_bi1.ndim

3

In [128]:
matriz_bi2 = np.random.random((4,4,4))
matriz_bi2.ndim

3

In [129]:
matriz_bi1.transpose()

array([[[0.82551145, 0.75702447, 0.35496962, 0.71070702],
        [0.10619492, 0.56239781, 0.4862526 , 0.20868981],
        [0.07084524, 0.78151744, 0.63110711, 0.7082305 ],
        [0.7124669 , 0.99765798, 0.56526989, 0.60582155]],

       [[0.06594912, 0.78533284, 0.76846832, 0.7971604 ],
        [0.80207753, 0.88640062, 0.01475294, 0.0513841 ],
        [0.92795872, 0.99877733, 0.97681767, 0.05142895],
        [0.98180599, 0.7288297 , 0.98367796, 0.49385031]],

       [[0.06031687, 0.83109745, 0.52203325, 0.81260405],
        [0.53083228, 0.87001532, 0.50609739, 0.08802734],
        [0.46272771, 0.11871717, 0.77389332, 0.10317148],
        [0.83349487, 0.45507218, 0.17820333, 0.37473742]],

       [[0.70734317, 0.1119558 , 0.57836048, 0.64039519],
        [0.39075805, 0.29470137, 0.93716861, 0.61424239],
        [0.08108519, 0.91430094, 0.47907545, 0.00601467],
        [0.09190924, 0.27992281, 0.39872234, 0.69359128]]])

In [130]:
matriz_bi2.transpose()

array([[[0.5920384 , 0.97129453, 0.09150862, 0.63403948],
        [0.52481475, 0.51544119, 0.76866111, 0.28251124],
        [0.73362252, 0.68293011, 0.88983006, 0.75134843],
        [0.78373774, 0.47995269, 0.13353773, 0.76305314]],

       [[0.3768301 , 0.89212453, 0.19596037, 0.44139576],
        [0.04689628, 0.41860958, 0.84576555, 0.79219622],
        [0.26899616, 0.43641706, 0.49668461, 0.11958473],
        [0.37637093, 0.40981134, 0.56968946, 0.49554498]],

       [[0.926403  , 0.1672731 , 0.32438955, 0.8556459 ],
        [0.52825449, 0.11014377, 0.93324077, 0.02474199],
        [0.2266108 , 0.54008321, 0.05636701, 0.5260437 ],
        [0.94912962, 0.98359266, 0.42859268, 0.52748164]],

       [[0.72859919, 0.16280831, 0.61300394, 0.9765795 ],
        [0.29148505, 0.97220101, 0.65447819, 0.93981838],
        [0.10780091, 0.88783849, 0.41946488, 0.34030542],
        [0.84702986, 0.50331438, 0.10441788, 0.9609407 ]]])

In [132]:
resultado = np.dot(matriz_bi1, matriz_bi2)
print(resultado)

[[[[1.1219669  0.59661874 1.48462301 1.22633315]
   [1.21649111 1.08026651 0.87366342 0.60808355]
   [0.2743627  0.65046943 0.63589568 0.64836411]
   [1.12709764 0.77435523 1.11281704 1.56839875]]

  [[1.17949593 0.36749371 1.01325272 0.69937508]
   [1.06663707 0.82229778 0.77714775 1.46503748]
   [1.15077502 1.18544651 0.98037744 0.85350778]
   [0.99093685 0.9393944  0.59606892 1.41365541]]

  [[0.93196651 0.22520451 0.73764906 0.44066792]
   [0.90204748 0.68682708 0.44372564 1.36533541]
   [1.14234569 1.07474149 0.94982546 0.85332192]
   [0.71661949 0.86191271 0.36976393 1.17668547]]

  [[1.62057737 0.5733209  1.45478762 0.97298595]
   [1.81140929 1.44801942 0.7678742  1.85677638]
   [1.5738151  1.43633677 1.23375144 1.43853443]
   [1.42548007 1.23748129 1.12084638 1.99046204]]]


 [[[1.55779759 0.58779772 1.41076155 0.96490315]
   [1.76140157 1.4126938  0.77211003 1.68098052]
   [1.42741489 1.28912761 1.07330536 1.33834857]
   [1.41172074 1.11115079 1.16342378 1.86777466]]

  [[1.66

In [140]:
np.save('Matriz01.txt', matriz_bi1)
np.save('Matriz02.txt', matriz_bi2)
np.save('Resultado.txt', resultado)

In [142]:
file = open('matriz_old.txt', 'w')
file.write(str(matriz_bi1))

775

In [144]:
file = open('matriz_old_02.txt', 'w')
file.write(str(matriz_bi2))

775

In [146]:
file = open('resultado.txt', 'w')
file.write(str(resultado))

3174

## Melhorias e funcionalidades pendentes  
  
  
Exercicio 1: Atualemte retorna uma lista com os valores vazios e media.
Sugestao de melhoria:  Ao inves de retornar uma lista somente com os valores vazios, retornar uma lista com os valores vazios e o nome cientifico, dessa forma quando a lista fosse plotada no grafico apareceria os labels correspondentes de cada especie.  
  
Documentacao do exercicio 1. Descrever em detalhes testes, dificuldades, bugs, etc.  
### Assign Taks: "Leticia" - Work in Progress
   
--------------------------------------------------------------------------------------  
Exercicio 2: Esta com um bug na funcao, esta sendo passado uma lista pela variavel path, entretanto a lista passada parece nao esta no formato correto, e esta retornando uma lista com o dobro de valores de linhas. Por enquanto existe tres funcoes "if" provisorias para a aplicacao nao falhar.  
  
Documentacao do exercicio 2.  
### Assign Task:" Lucas " Status: Work in Progress 
  
--------------------------------------------------------------------------------------  
Exercicio 3: A logica dos filtros do exercicio 3 esta incompleta, e os unicos filtros aplicaveis ate o momento sao Municipios e Familias, fazer o restante dos filtros.  

Documentar os filtros do exercicio 3
### Assign Task: "Savio" - Status: Work in Progress 
  
--------------------------------------------------------------------------------------  
Exercicio 4: Importar de outro grupo a classe que verifica se os dados estao corretos e implementar no codigo principal. Fazer o metodo funcionar e escrever a lista de resposta.
  
Documentacao do exercicio 4.
### Assign Task:" Jessica " - Status: Work in Progress 
 