## EXERCICIOS DA AULA NUMPY

In [6]:
import numpy as np

a= np.random.random((2,3))
print(a)

b = a.reshape((3,2))

print(b)

[[0.1969017  0.75717664 0.13586722]
 [0.74355199 0.46492196 0.0309963 ]]
[[0.1969017  0.75717664]
 [0.13586722 0.74355199]
 [0.46492196 0.0309963 ]]


In [10]:
a = np.arange(1,11,1)
b = a.reshape((2,5))

print(a,b)

[ 1  2  3  4  5  6  7  8  9 10] [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [38]:
c = np.random.random((2,3))

d= c.transpose()

arquivo = open('Documentos/AULAS/numpy.txt', 'w')
arquivo.write(str(c))
arquivo.write(str(d))

#np.savetxt('Documentos/AULAS/numpy.txt', c)
#np.savetxt('Documentos/AULAS/numpy.txt', d)


e =np.dot(c,d)
arqui = open('Documentos/AULAS/numpy2.txt', 'w')
arqui.write(str(e))

50

In [20]:
pwd

'/home/leticia'

In [39]:
x = np.random.random((2,3))
y = np.random.random((2,3))

res=np.add(x,y)

print(res)

[[1.08138851 1.80983555 0.13019242]
 [1.30528401 1.49486601 1.47728422]]


## NUMPY LISTA OUTRA

In [12]:
import numpy as np
a = np.zeros((1,10))
print(a.nbytes)

b = np.random.random((2,3,10))
print(b.nbytes)

80
480


In [16]:
a = np.zeros((1,10))
a[0,4]=1

print(a)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [19]:
varia=np.arange(10,49)

print(varia)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [29]:
vet=np.arange(10,49)
print(vet)
avesso = [vet[i] for i in range(len(vet))]

print(avesso)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]
[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48]


In [41]:
matriz_cresc = np.random.randint(0,9,(3,3))
print(matriz_cresc)

[[5 5 0]
 [0 0 2]
 [7 2 0]]


In [31]:
n=np.full((2,2),7) 
print("full: ",n)

full:  [[7 7]
 [7 7]]


In [48]:
ide = np.identity(3)
print(ide)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [55]:
rand3 = np.random.random((3,3,3))
print(rand3)

[[[0.49570584 0.46414646 0.91557807]
  [0.65446564 0.04373585 0.53090768]
  [0.84661485 0.92759124 0.75137959]]

 [[0.56790679 0.95672164 0.71693586]
  [0.08052833 0.20812865 0.65707056]
  [0.48734305 0.8969018  0.11330856]]

 [[0.26462781 0.97778625 0.86173869]
  [0.97865638 0.99686545 0.44026192]
  [0.65845493 0.62702957 0.02373282]]]


In [63]:
rand10 = np.random.random((10,10))
print(rand10)

print('\n',rand10.max(), '\n')

print('\n',rand10.min(), '\n')

[[0.85139474 0.28345981 0.75253972 0.37888835 0.22265229 0.54664931
  0.83859184 0.32815181 0.44493208 0.05615659]
 [0.03168087 0.70973512 0.77209564 0.39544166 0.61784731 0.55932048
  0.61736423 0.00129702 0.93048217 0.8900458 ]
 [0.70503763 0.61965732 0.69890468 0.87330112 0.37305612 0.20398756
  0.7857784  0.33157113 0.92069424 0.10166612]
 [0.0225658  0.28803164 0.41347443 0.30984409 0.024746   0.80855258
  0.68364047 0.37338996 0.39371183 0.18936308]
 [0.80042263 0.83352524 0.1430792  0.57325383 0.17424844 0.68699591
  0.38061247 0.80147622 0.51001973 0.17025754]
 [0.38903304 0.73809932 0.83800404 0.56018632 0.44926656 0.81126091
  0.8621714  0.16504901 0.15337961 0.56628221]
 [0.78908333 0.63984641 0.43756306 0.31570849 0.0846288  0.63656913
  0.289979   0.51352421 0.340394   0.72252415]
 [0.12271308 0.7453649  0.66577978 0.23701824 0.15318571 0.94920792
  0.09379909 0.66219107 0.2972876  0.51368874]
 [0.38073939 0.4177599  0.06061637 0.26111339 0.49075025 0.98653853
  0.69238956

In [70]:
rand30 = np.random.random((1,30))
print(rand30)

print('\n',rand30.mean())

[[0.88374537 0.32836464 0.38226329 0.42322405 0.29864202 0.43906147
  0.20771167 0.66139986 0.00621195 0.73659893 0.73890188 0.6641583
  0.97088565 0.22266823 0.84112717 0.58548286 0.16735082 0.19350137
  0.05732676 0.26540309 0.93274208 0.47455265 0.55461868 0.64558622
  0.13125257 0.15285889 0.03693124 0.86193782 0.2235647  0.047678  ]]

 0.4378584080342877


In [85]:
n = 7
matrix = np.zeros((n,n))

matrix[0]=1
matrix[:,0]=1
matrix[n-1]=1
matrix[:,n-1]=1


print(matrix)


[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [97]:
m1234 = np.zeros((5,5))
k=1
for i in range(-1, m1234.shape[1]-1):
    for j in range(m1234.shape[0]):
        if i==j:
            m1234[k,j]=k
            k=k+1

print(m1234)

#Funciona p qqr valor, matrix 7x7 por exemplo imprime 1-6

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [106]:
mtz = np.random.random((5,5))
print(mtz, '\n')

for i in range(mtz.shape[1]):
    media=mtz[i,:].mean()
    print(media, '\n')
    for j in range(mtz.shape[0]):
        mtz[i][j] = mtz[i][j] - media
        
print(mtz)

[[0.93385493 0.03266881 0.27713018 0.71219329 0.6766357 ]
 [0.30416548 0.87417793 0.83202973 0.53052753 0.6617861 ]
 [0.40272614 0.09218459 0.38273325 0.67915816 0.78936569]
 [0.50301401 0.24196029 0.29599834 0.01232425 0.49698064]
 [0.288883   0.73697637 0.0166349  0.2853888  0.27049552]] 

0.5264965826593963 

0.640537353401413 

0.46923356666410115 

0.3100555053081654 

0.3196757200829223 

[[ 0.40735835 -0.49382777 -0.2493664   0.18569671  0.15013911]
 [-0.33637187  0.23364058  0.19149238 -0.11000983  0.02124874]
 [-0.06650742 -0.37704898 -0.08650032  0.2099246   0.32013212]
 [ 0.1929585  -0.06809522 -0.01405716 -0.29773126  0.18692514]
 [-0.03079272  0.41730065 -0.30304082 -0.03428692 -0.0491802 ]]


In [131]:
import numpy as np
from PIL import Image

array = np.zeros([100, 200, 4], dtype=np.uint8)
array[:,:100] = [255, 120, 0, 0] #Orange left side
array[:,100:] = [0, 0, 255, 0]   #Blue right side

# Set transparency depending on x position
for x in range(200):
    for y in range(100):
        array[y, x, 3] = x


img = Image.fromarray(array)
#img.show()

In [142]:
matriz = np.random.randint(0,255,(1000,1000,3)) #dimensoes da imagem e canais

img = Image.fromarray(matriz.astype('uint8'))
img.show()

print(matriz)

[[[ 67 107 168]
  [ 59 209 226]
  [198 121 225]
  ...
  [141  97 183]
  [  7   1  38]
  [131 251 108]]

 [[168  97  26]
  [105 109 244]
  [ 30 233 162]
  ...
  [ 98 251   8]
  [100  85 151]
  [149 197 223]]

 [[ 97 236 215]
  [140  69 144]
  [249 163 252]
  ...
  [ 16 180 250]
  [113  13 131]
  [182 244 178]]

 ...

 [[ 76 111  47]
  [179  96 177]
  [ 48 199  83]
  ...
  [ 34   6  12]
  [184 140  13]
  [204 123  33]]

 [[243 140 152]
  [ 84  52 249]
  [152 247 207]
  ...
  [240 106  32]
  [ 64  75   7]
  [101  60 243]]

 [[239  61 227]
  [131 231 243]
  [253 250 157]
  ...
  [ 90 177 235]
  [  5  13 238]
  [  5 223  14]]]


## EXERCICIO PANDAS CHAT

In [1]:
pwd

'/home/leticia'

In [34]:
import pandas as pd
import numpy as np
file = pd.read_csv('Documentos/AULAS/Auto.csv', sep=',', na_values='?')
print(file.loc[32])

mpg                     25
cylinders                4
displacement            98
horsepower             NaN
weight                2046
acceleration            19
year                    71
origin                   1
name            ford pinto
Name: 32, dtype: object


In [44]:
dfexcl=file[file['horsepower'].isnull()]
print(dfexcl)


new_df = file.dropna()
print('\n',new_df.loc[31]) #AQUI ELE DELETOU O INDICE 32, NAO CONSEGUI IMPRIMIR

newdf = file.fillna(0)
print('\n',newdf.loc[32]) #AQUI ELE SUBSTITUIU POR ZERO
# print(file[file['mpg'] == '?'])

# print(file[file['cylinders'] == '?'])

#print(file[file['displacement'] == '?'])

# print(file[file['weight'] == '?'])

# print(file[file['acceleration'] == '?'])

# print(file[file['year'] == '?'])

# print(file[file['origin'] == '?'])

# print(file[file['name'] == '?'])

      mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
32   25.0          4          98.0         NaN    2046          19.0    71   
126  21.0          6         200.0         NaN    2875          17.0    74   
330  40.9          4          85.0         NaN    1835          17.3    80   
336  23.6          4         140.0         NaN    2905          14.3    80   
354  34.5          4         100.0         NaN    2320          15.8    81   

     origin                  name  
32        1            ford pinto  
126       1         ford maverick  
330       2  renault lecar deluxe  
336       1    ford mustang cobra  
354       2           renault 18i  

 mpg                        25
cylinders                   4
displacement              113
horsepower                 95
weight                   2228
acceleration               14
year                       71
origin                      3
name            toyota corona
Name: 31, dtype: object

 mpg              

In [46]:
dfmedio = file.fillna(file['horsepower'].mean())
print(dfmedio.loc[32])

mpg                     25
cylinders                4
displacement            98
horsepower         104.469
weight                2046
acceleration            19
year                    71
origin                   1
name            ford pinto
Name: 32, dtype: object


## PANDAS LISTA GIT

In [49]:
file.head()


mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
0  18.0          8         307.0       130.0    3504          12.0    70   
1  15.0          8         350.0       165.0    3693          11.5    70   
2  18.0          8         318.0       150.0    3436          11.0    70   
3  16.0          8         304.0       150.0    3433          12.0    70   
4  17.0          8         302.0       140.0    3449          10.5    70   

   origin                       name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [48]:
file.tail()

mpg  cylinders  displacement  horsepower  weight  acceleration  year  \
392  27.0          4         140.0        86.0    2790          15.6    82   
393  44.0          4          97.0        52.0    2130          24.6    82   
394  32.0          4         135.0        84.0    2295          11.6    82   
395  28.0          4         120.0        79.0    2625          18.6    82   
396  31.0          4         119.0        82.0    2720          19.4    82   

     origin             name  
392       1  ford mustang gl  
393       2        vw pickup  
394       1    dodge rampage  
395       1      ford ranger  
396       1       chevy s-10

In [138]:
carros = pd.read_csv('Documentos/AULAS/exercicios/carros.csv', sep=',')
#print(carros)
preco_medio = carros[['company','price']].groupby('company').mean().sort_values(by='price',ascending=False).head(1)
#preco_max = preco_medio.iloc[0]
print(preco_medio)
#print(preco_max.index)
print('O preco medio mais caro eh ', preco_medio['price'].values[0], 'da empresa', preco_medio.index.values[0])

           price
company         
porsche  35528.0
O preco medio mais caro eh  35528.0 da empresa porsche


In [139]:
preco_medio_total=carros['price'].mean()
print(preco_medio_total)

15387.0


In [140]:
max_hp=carros['horsepower'].max()
min_hp=carros['horsepower'].min()

print(min_hp, max_hp)

48 288


In [137]:
info_toyota = carros.loc[carros['company']=='toyota']
print(info_toyota)

    index company body-style  wheel-base  length engine-type num-of-cylinders  \
48     66  toyota  hatchback        95.7   158.7         ohc             four   
49     67  toyota  hatchback        95.7   158.7         ohc             four   
50     68  toyota  hatchback        95.7   158.7         ohc             four   
51     69  toyota      wagon        95.7   169.7         ohc             four   
52     70  toyota      wagon        95.7   169.7         ohc             four   
53     71  toyota      wagon        95.7   169.7         ohc             four   
54     79  toyota      wagon       104.5   187.8        dohc              six   

    horsepower  average-mileage    price  
48          62               35   5348.0  
49          62               31   6338.0  
50          62               31   6488.0  
51          62               31   6918.0  
52          62               27   7898.0  
53          62               27   8778.0  
54         156               19  15750.0  


In [141]:
#filtra por cilindro e salva em csv  (num-of-cylinders)

carros_agrupados = carros.groupby('num-of-cylinders')
print(carros_agrupados)

